{
    "author": "Exo Software",
    "category": "Generic Modules/Accounting",
    "demo_xml": [],
    "depends": [
        "base",
        "account",
        "contacts",
        "ptplus_accounting",
        "ptplus_reports",
        "ptplus_accounting_reports",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/l10n_pt_cope_code.xml",
        "report/report_cope.xml",
        "views/account_journal_views.xml",
        "views/account_payment_register_views.xml",
        "views/account_payment_views.xml",
        "views/l10n_pt_cope_code.xml",
        "views/res_config_view.xml",
        "wizards/l10n_pt_cope_statement_wizard.xml",
    ],
    "init_xml": [],
    "installable": True,
    "license": "OPL-1",
    "name": "Portugal - COPE Report",
    "test": [],
    "version": "19.0.1.0.0",
    "website": "https://exosoftware.pt",
}
