{
    "name": "Portugal - Intrastat Community",
    "author": "Exo Software",
    "version": "19.0.5.0.0",
    "category": "Localization",
    "license": "OPL-1",
    "countries": ["pt"],
    "depends": ["ptplus", "account", "intrastat_product"],
    "summary": "Intrastat report and csv for the portuguese localization",
    "data": [
        "security/ir.model.access.csv",
        "security/ir_rules.xml",
        "views/account_move_views.xml",
        "views/intrastat_views.xml",
        "views/res_partner_views.xml",
        "views/res_country_views.xml",
        "views/res_company_views.xml",
        "wizard/intrastat_wizard_views.xml",
        "data/intrastat_port_aeroport.xml",
        "data/intrastat_hs_code.xml",
    ],
    "website": "https://exosoftware.pt",
    "installable": True,
    "auto_install": False,
}
