import logging

from odoo import SUPERUSER_ID, api

_logger = logging.getLogger(__name__)


def migrate(cr, version):
    env = api.Environment(cr, SUPERUSER_ID, {})

    _logger.info("Migrating data using temporary column...")

    # The record was just introduced if it doesn't have a 'code_tmp' set
    cr.execute(
        """
        SELECT *
        FROM l10n_pt_company_eac
        WHERE code_tmp IS NULL
    """
    )
    new_eacs = cr.fetchall()

    # It's an old record if it has a 'code_tmp'
    cr.execute(
        """
        SELECT *
        FROM l10n_pt_company_eac
        WHERE code_tmp IS NOT NULL
    """
    )
    old_eacs = cr.fetchall()
    if new_eacs:
        # Go through the new records
        for new_record in new_eacs:
            to_delete = False
            for old_record in old_eacs:
                # In case of the record's code being changed
                # name -> position [5]
                # code -> position [4]
                # type -> position [6]
                # parent_id -> position [1]
                # id -> position [0]
                if (
                    new_record[5] == old_record[5]
                    and len(new_record[4]) == len(old_record[4])
                    and new_record[4] != old_record[4]
                ):
                    try:
                        # XML id of the parent should be the code
                        # of the new record without its last digit
                        parent_xml = f"ptplus_partner_eac.company_eac_{new_record[6]}{new_record[4][:-1]}"
                        parent_id = env.ref(parent_xml).id
                        cr.execute(
                            """
                            UPDATE l10n_pt_company_eac
                            SET code = %s, type = %s, parent_id = %s
                            WHERE id = %s;
                            """,
                            (
                                new_record[4],
                                new_record[6],
                                parent_id,
                                old_record[0],
                            ),
                        )
                    except Exception:
                        try:
                            parent_xml = (
                                f"ptplus_partner_eac.company_eac_{new_record[6]}0"
                            )
                            parent_id = env.ref(parent_xml).id

                            cr.execute(
                                """
                                UPDATE l10n_pt_company_eac
                                SET code      = %s,
                                    type      = %s,
                                    parent_id = %s
                                WHERE id = %s;
                                """,
                                (
                                    new_record[4],
                                    new_record[6],
                                    parent_id,
                                    old_record[0],
                                ),
                            )
                        except Exception as e:
                            _logger.error(
                                f"(1) Could not update record: {new_record[5]}\n"
                                f"It may not exist or another error occurred: {e}"
                            )
                    to_delete = True
                    continue
                # In case of the record's name being changed
                if new_record[4] == old_record[4]:
                    try:
                        parent_xml = f"ptplus_partner_eac.company_eac_{new_record[6]}{new_record[4][:-1]}"
                        parent_id = env.ref(parent_xml).id
                        cr.execute(
                            """
                            UPDATE l10n_pt_company_eac
                            SET code      = %s,
                                type      = %s,
                                parent_id = %s
                            WHERE id = %s;
                            """,
                            (new_record[4], new_record[6], parent_id, old_record[0]),
                        )
                    except Exception:
                        try:
                            parent_xml = (
                                f"ptplus_partner_eac.company_eac_{new_record[6]}0"
                            )
                            parent_id = env.ref(parent_xml).id

                            cr.execute(
                                """
                                UPDATE l10n_pt_company_eac
                                SET code      = %s,
                                    type      = %s,
                                    parent_id = %s
                                WHERE id = %s;
                                """,
                                (
                                    new_record[4],
                                    new_record[6],
                                    parent_id,
                                    old_record[0],
                                ),
                            )
                        except Exception as e:
                            _logger.error(
                                f"(4) Could not update record: {new_record[5]}\n"
                                f"It may not exist or another error occurred: {e}"
                            )
                    to_delete = True
                    continue

            # To prevent duplicates, delete new ones that were also found in old the list
            if to_delete:
                try:
                    cr.execute(
                        """
                        DELETE
                        FROM l10n_pt_company_eac
                        WHERE id = %s;
                        """,
                        (new_record[0],),
                    )
                except Exception as e:
                    _logger.warning(
                        f"(2) Could not drop record: {new_record[5]}\n"
                        f"It may not exist or another error occurred: {e}"
                    )
        # These are the old records that were not found in the new list,
        # calculated in a different script
        # flake8: noqa: E501
        cr.execute(
            """
            UPDATE l10n_pt_company_eac
            SET active = false
            WHERE name IN (
                'Agricultura, produção animal, caça e actividades dos serviços relacionados',
                'Cerealicultura (excepto arroz), leguminosas secas e sementes oleaginosas',
                'Cerealicultura (excepto arroz)',
                'Cultura de leguminosas secas e sementes oleaginosas',
                'Cultura de arroz',
                'Cultura de produtos hortícolas, raízes e tubérculos',
                'Cultura de cana-de-açúcar',
                'Cultura de tabaco',
                'Cultura de plantas têxteis',
                'Outras culturas temporárias',
                'Cultura de flores e de plantas ornamentais',
                'Outras culturas temporárias, n.e.',
                'Culturas permanentes',
                'Viticultura',
                'Cultura de frutos tropicais e subtropicais',
                'Cultura de citrinos',
                'Cultura de pomóideas e prunóideas',
                'Cultura de outros frutos (inclui casca rija), em árvores e arbustos',
                'Cultura de frutos de casca rija',
                'Cultura de outros frutos em árvores e arbustos',
                'Cultura de frutos oleaginosos',
                'Olivicultura',
                'Cultura de outros frutos oleaginosos',
                'Cultura de plantas destinadas à preparação de bebidas',
                'Cultura de especiarias, plantas aromáticas, medicinais e farmacêuticas',
                'Outras culturas permanentes',
                'Cultura de materiais de propagação vegetativa',
                'Produção animal',
                'Criação de bovinos para produção de leite',
                'Criação de outros bovinos (excepto para produção de leite) e búfalos',
                'Criação de equinos, asininos e muares',
                'Criação de camelos e camelídeos',
                'Criação de ovinos e caprinos',
                'Suinicultura',
                'Avicultura',
                'Outra produção animal',
                'Apicultura',
                'Cunicultura',
                'Criação de animais de companhia',
                'Outra produção animal, n.e.',
                'Agricultura e produção animal combinadas',
                'Actividades dos serviços relacionados com a agricultura e com a produção animal',
                'Actividades dos serviços relacionados com a agricultura',
                'Actividades dos serviços relacionados com a produção animal, excepto',
                'Preparação de produtos agrícolas para venda',
                'Preparação e tratamento de sementes para propagação',
                'Caça, repovoamento cinegético e actividades dos serviços relacionados',
                'Caça e repovoamento cinegético',
                'Actividades dos serviços relacionados com caça e repovoamento cinegético',
                'Silvicultura e exploração florestal',
                'Silvicultura e outras actividades florestais',
                'Exploração florestal',
                'Extracção de cortiça, resina e apanha de outros produtos florestais, excepto madeira',
                'Actividades dos serviços relacionados com a silvicultura e exploração florestal',
                'Pesca e aquicultura',
                'Pesca',
                'Pesca marítima, apanha de algas e de outros produtos do mar',
                'Pesca marítima',
                'Apanha de algas e de outros produtos do mar',
                'Pesca em águas interiores e apanha de produtos em águas interiores',
                'Pesca em águas interiores',
                'Apanha de produtos em águas interiores',
                'Aquicultura',
                'Aquicultura em águas salgadas e salobras',
                'Aquicultura em águas doces',
                'INDÚSTRIAS EXTRACTIVAS',
                'Extracção de hulha e lenhite',
                'Extracção de hulha (inclui antracite)',
                'Extracção de lenhite',
                'Extracção de petróleo bruto e gás natural',
                'Extracção de petróleo bruto',
                'Extracção de gás natural',
                'Extracção e preparação de minérios metálicos',
                'Extracção e preparação de minérios de ferro',
                'Extracção e preparação de minérios metálicos não ferrosos',
                'Extracção e preparação de minérios de urânio e de tório',
                'Extracção e preparação de outros minérios metálicos não ferrosos',
                'Outras indústrias extractivas',
                'Extracção de pedra, areia e argila',
                'Extracção de rochas ornamentais e de outras pedras para construção, de calcário, de gesso, de cré e de ardósia',
                'Extracção de mármore e outras rochas carbonatadas',
                'Extracção de granito ornamental e rochas similares',
                'Extracção de calcário e cré',
                'Extracção de gesso',
                'Extracção de ardósia',
                'Extracção de saibro, areia e pedra britada; extracção de argilas e caulino',
                'Extracção de saibro, areia e pedra britada',
                'Extracção de argilas e caulino',
                'Indústrias extractivas, n.e.',
                'Extracção de minerais para a indústria química e para a fabricação de adubos',
                'Extracção da turfa',
                'Extracção de sal',
                'Extracção de sal marinho',
                'Extracção de sal gema',
                'Outras indústrias extractivas, n.e.',
                'Extracção de feldspato',
                'Extracção de outros minerais não metálicos, n.e.',
                'Actividades dos serviços relacionados com as indústrias extractivas',
                'Actividades dos serviços relacionados com a extracção de petróleo e gás, excepto a prospecção',
                'Outras actividades dos serviços relacionados com as indústrias extractivas',
                'INDÚSTRIAS TRANSFORMADORAS',
                'Indústrias alimentares',
                'Abate de animais, preparação e conservação de carne e de produtos à base de carne',
                'Abate de gado (produção de carne)',
                'Abate de aves (produção de carne)',
                'Fabricação de produtos à base de carne',
                'Preparação e conservação de peixes, crustáceos e moluscos',
                'Preparação de produtos da pesca e da aquicultura',
                'Congelação de produtos da pesca e da aquicultura',
                'Conservação de produtos da pesca e da aquicultura em azeite e outros óleos vegetais e outros molhos',
                'Salga, secagem e outras actividades de transformação de produtos da pesca e aquicultura',
                'Preparação e conservação de frutos e de produtos hortícolas',
                'Preparação e conservação de batatas',
                'Fabricação de sumos de frutos e de produtos hortícolas',
                'Outra preparação e conservação de frutos e de produtos hortícolas',
                'Congelação de frutos e de produtos hortícolas',
                'Secagem e desidratação de frutos e de produtos hortícolas',
                'Fabricação de doces, compotas, geleias e marmelada',
                'Descasque e transformação de frutos de casca rija comestíveis',
                'Preparação e conservação de frutos e de produtos hortícolas por outros processos',
                'Produção de óleos e gorduras animais e vegetais',
                'Produção de óleos e gorduras',
                'Produção de óleos e gorduras animais brutos',
                'Produção de azeite',
                'Produção de óleos vegetais brutos (excepto azeite)',
                'Refinação de azeite, óleos e gorduras',
                'Fabricação de margarinas e de gorduras alimentares similares',
                'Indústria de lacticínios',
                'Indústrias do leite e derivados',
                'Fabricação de gelados e sorvetes',
                'Transformação de cereais e leguminosas; fabricação de amidos, de féculas e de produtos afins',
                'Transformação de cereais e leguminosas',
                'Moagem de cereais',
                'Descasque, branqueamento e outros tratamentos do arroz',
                'Transformação de cereais e leguminosas, n.e.',
                'Fabricação de amidos, féculas e produtos afins',
                'Fabricação de produtos de padaria e outros produtos à base de farinha',
                'Panificação e pastelaria',
                'Panificação',
                'Pastelaria',
                'Fabricação de bolachas, biscoitos, tostas e pastelaria de conservação',
                'Fabricação de massas alimentícias, cuscuz e similares',
                'Fabricação de outros produtos alimentares',
                'Indústria do açúcar',
                'Indústria do cacau, do chocolate e dos produtos de confeitaria',
                'Fabricação de cacau e de chocolate',
                'Fabricação de produtos de confeitaria',
                'Indústria do café e do chá',
                'Fabricação de condimentos e temperos',
                'Fabricação de refeições e pratos pré-cozinhados',
                'Fabricação de alimentos homogeneizados e dietéticos',
                'Fabricação de outros produtos alimentares, n.e.',
                'Fabricação de fermentos, leveduras e adjuvantes para panificação e pastelaria',
                'Fabricação de caldos, sopas e sobremesas',
                'Fabricação de outros produtos alimentares diversos, n.e.',
                'Fabricação de alimentos para animais',
                'Fabricação de alimentos para animais de criação',
                'Fabricação de pré-misturas',
                'Fabricação de alimentos para animais de criação (excepto para aquicultura)',
                'Fabricação de alimentos para aquicultura',
                'Fabricação de alimentos para animais de companhia',
                'Indústria das bebidas',
                'Fabricação de bebidas alcoólicas destiladas',
                'Fabricação de aguardentes preparadas',
                'Fabricação de aguardentes não preparadas',
                'Produção de licores e de outras bebidas destiladas',
                'Indústria do vinho',
                'Produção de vinhos comuns e licorosos',
                'Produção de vinhos espumantes e espumosos',
                'Fabricação de cidra e outras bebidas fermentadas de frutos',
                'Fabricação de vermutes e de outras bebidas fermentadas não destiladas',
                'Fabricação de cerveja',
                'Fabricação de malte',
                'Fabricação de refrigerantes; produção de águas minerais naturais e de outras águas engarrafadas',
                'Engarrafamento de águas minerais naturais e de nascente',
                'Fabricação de refrigerantes e de outras bebidas não alcoólicas, n.e.',
                'Indústria do tabaco',
                'Fabricação de têxteis',
                'Preparação e fiação de fibras têxteis',
                'Preparação e fiação de fibras do tipo algodão',
                'Preparação e fiação de fibras do tipo lã',
                'Preparação e fiação da seda e preparação e texturização de filamentos sintéticos e artificiais',
                'Fabricação de linhas de costura',
                'Preparação e fiação de linho e outras fibras têxteis',
                'Tecelagem de têxteis',
                'Tecelagem de fio do tipo algodão',
                'Tecelagem de fio do tipo lã',
                'Tecelagem de fio do tipo seda e de outros têxteis',
                'Acabamento de têxteis',
                'Branqueamento e tingimento',
                'Estampagem',
                'Acabamento de fios, tecidos e artigos têxteis, n.e.',
                'Fabricação de outros têxteis',
                'Fabricação de tecidos de malha',
                'Fabricação de artigos têxteis confeccionados, excepto vestuário',
                'Fabricação de tapetes e carpetes',
                'Fabricação de cordoaria e redes',
                'Fabricação de cordoaria',
                'Fabricação de redes',
                'Fabricação de não tecidos e respectivos artigos, excepto vestuário',
                'Fabricação de têxteis para uso técnico e industrial',
                'Fabricação de passamanarias e sirgarias',
                'Fabricação de têxteis para uso técnico e industrial,n.e.',
                'Fabricação de outros têxteis, n.e.',
                'Fabricação de bordados',
                'Fabricação de rendas',
                'Fabricação de outros têxteis diversos, n.e.',
                'Indústria do vestuário',
                'Confecção de artigos de vestuário, excepto artigos de peles com pêlo',
                'Confecção de vestuário em couro',
                'Confecção de vestuário de trabalho',
                'Confecção de outro vestuário exterior',
                'Confecção de outro vestuário exterior em série',
                'Confecção de outro vestuário exterior por medida',
                'Actividades de acabamento de artigos de vestuário',
                'Confecção de vestuário interior',
                'Confecção de outros artigos e acessórios de vestuário',
                'Fabricação de artigos de peles com pêlo',
                'Fabricação de artigos de malha',
                'Fabricação de meias e similares de malha',
                'Fabricação de outro vestuário de malha',
                'Indústria do couro e dos produtos do couro',
                'Curtimenta e acabamento de peles sem pêlo e com pêlo; fabricação de artigos de viagem e de uso pessoal, de marroquinaria, de correeiro e de seleiro',
                'Curtimenta e acabamento de peles sem pêlo e com pêlo',
                'Curtimenta e acabamento de peles sem pêlo',
                'Fabricação de couro reconstituído',
                'Curtimenta e acabamento de peles com pêlo',
                'Fabricação de artigos de viagem e de uso pessoal, de marroquinaria, de correeiro e de seleiro',
                'Indústria do calçado',
                'Fabricação de calçado',
                'Fabricação de componentes para calçado',
                'Indústrias da madeira e da cortiça e suas obras, excepto mobiliário; fabricação de obras de cestaria e de espartaria',
                'Serração, aplainamento e impregnação da madeira',
                'Serração de madeira',
                'Impregnação de madeira',
                'Fabricação de artigos de madeira, de cortiça, de espartaria e de cestaria, excepto mobiliário',
                'Fabricação de folheados e painéis à base de madeira',
                'Fabricação de painéis de partículas de madeira',
                'Fabricação de painéis de fibras de madeira',
                'Fabricação de folheados, contraplacados, lamelados e de outros painéis',
                'Parqueteria',
                'Fabricação de outras obras de carpintaria para a construção',
                'Fabricação de embalagens de madeira',
                'Fabricação de outras obras de madeira, de cestaria e espartaria; indústria da cortiça',
                'Fabricação de outras obras de madeira',
                'Fabricação de obras de cestaria e de espartaria',
                'Indústria de preparação da cortiça',
                'Fabricação de rolhas de cortiça',
                'Fabricação de outros produtos de cortiça',
                'Fabricação de pasta, de papel, cartão e seus artigos',
                'Fabricação de pasta, de papel e cartão (excepto canelado)',
                'Fabricação de pasta',
                'Fabricação de papel e de cartão (excepto canelado)',
                'Fabricação de papel e de cartão canelados e de artigos de papel e de cartão',
                'Fabricação de papel e de cartão canelados e de embalagens de papel e cartão',
                'Fabricação de papel e de cartão canelados (inclui embalagens)',
                'Fabricação de outras embalagens de papel e de cartão',
                'Fabricação de artigos de papel para uso doméstico e sanitário',
                'Fabricação de artigos de papel para papelaria',
                'Fabricação de papel de parede',
                'Fabricação de outros artigos de pasta de papel, de papel e de cartão',
                'Impressão e reprodução de suportes gravados',
                'Impressão e actividades dos serviços relacionados com a impressão',
                'Impressão de jornais',
                'Outra impressão',
                'Actividades de preparação da impressão e de produtos media',
                'Encadernação e actividades relacionadas',
                'Reprodução de suportes gravados',
                'Fabricação de coque, de produtos petrolíferos refinados e de aglomerados de combustíveis',
                'Fabricação de produtos de coqueria',
                'Fabricação de produtos petrolíferos refinados e de aglomerados de combustíveis',
                'Fabricação de produtos petrolíferos refinados',
                'Fabricação de produtos petrolíferos a partir de resíduos',
                'Fabricação de briquetes e aglomerados de hulha e lenhite',
                'Fabricação de produtos químicos e de fibras sintéticas ou artificiais, excepto produtos farmacêuticos',
                'Fabricação de produtos químicos de base, adubos e compostos azotados, matérias plásticas e borracha sintética, sob formas primárias',
                'Fabricação de gases industriais',
                'Fabricação de corantes e pigmentos',
                'Fabricação de outros produtos químicos inorgânicos de base',
                'Fabricação de outros produtos químicos orgânicos de base',
                'Fabricação de resinosos e seus derivados',
                'Fabricação de carvão (vegetal e animal) e produtos associados',
                'Fabricação de álcool etílico de fermentação',
                'Fabricação de outros produtos químicos orgânicos de base, n.e.',
                'Fabricação de adubos e de compostos azotados',
                'Fabricação de adubos químicos ou minerais e de compostos azotados',
                'Fabricação de adubos orgânicos e organo-minerais',
                'Fabricação de matérias plásticas sob formas primárias',
                'Fabricação de borracha sintética sob formas primárias',
                'Fabricação de pesticidas e de outros produtos agroquímicos',
                'Fabricação de tintas, vernizes e produtos similares; mastiques; tintas de impressão',
                'Fabricação de tintas (excepto impressão), vernizes, mastiques e produtos similares',
                'Fabricação de tintas de impressão',
                'Fabricação de pigmentos preparados, composições vitrificáveis e afins',
                'Fabricação de sabões e detergentes, produtos de limpeza e de polimento, perfumes e produtos de higiene',
                'Fabricação de sabões e detergentes, produtos de limpeza e de polimento',
                'Fabricação de sabões, detergentes e glicerina',
                'Fabricação de produtos de limpeza, polimento e protecção',
                'Fabricação de perfumes, de cosméticos e de produtos de higiene',
                'Fabricação de outros produtos químicos',
                'Fabricação de explosivos e artigos de pirotecnia',
                'Fabricação de colas',
                'Fabricação de óleos essenciais',
                'Fabricação de outros produtos químicos, n.e.',
                'Fabricação de biodiesel',
                'Fabricação de produtos químicos auxiliares para uso industrial',
                'Fabricação de óleos e massas lubrificantes, com exclusão da efectuada nas refinarias',
                'Fabricação de outros produtos químicos diversos, n.e.',
                'Fabricação de fibras sintéticas ou artificiais',
                'Fabricação de produtos farmacêuticos de base e de preparações farmacêuticas',
                'Fabricação de produtos farmacêuticos de base',
                'Fabricação de preparações farmacêuticas',
                'Fabricação de medicamentos',
                'Fabricação de outras preparações e de artigos farmacêuticos',
                'Fabricação de artigos de borracha e de matérias plásticas',
                'Fabricação de artigos de borracha',
                'Fabricação de pneus e câmaras-de-ar; reconstrução de pneus',
                'Fabricação de pneus e câmaras-de-ar',
                'Reconstrução de pneus',
                'Fabricação de outros produtos de borracha',
                'Fabricação de componentes de borracha para calçado',
                'Fabricação de outros produtos de borracha, n.e.',
                'Fabricação de artigos de matérias plásticas',
                'Fabricação de chapas, folhas, tubos e perfis de plástico',
                'Fabricação de embalagens de plástico',
                'Fabricação de artigos de plástico para a construção',
                'Fabricação de outros artigos de plástico',
                'Fabricação de componentes de plástico para calçado',
                'Fabricação de outros artigos de plástico, n.e.',
                'Fabricação de outros produtos minerais não metálicos',
                'Fabricação de vidro e artigos de vidro',
                'Fabricação de vidro plano',
                'Moldagem e transformação de vidro plano',
                'Fabricação de vidro de embalagem e cristalaria (vidro oco)',
                'Fabricação de vidro de embalagem',
                'Cristalaria',
                'Fabricação de fibras de vidro',
                'Fabricação e transformação de outro vidro (inclui vidro técnico)',
                'Fabricação de produtos cerâmicos refractários',
                'Fabricação de produtos cerâmicos para a construção',
                'Fabricação de azulejos, ladrilhos, mosaicos e placas de cerâmica',
                'Fabricação de azulejos',
                'Fabricação de ladrilhos, mosaicos e placas de cerâmica',
                'Fabricação de tijolos, telhas e de outros produtos cerâmicos para a construção',
                'Fabricação de tijolos',
                'Fabricação de telhas',
                'Fabricação de abobadilhas',
                'Fabricação de outros produtos cerâmicos para a construção',
                'Fabricação de outros produtos de porcelana e cerâmicos não refractários',
                'Fabricação de artigos cerâmicos de uso doméstico e ornamental',
                'Olaria de barro',
                'Fabricação de artigos de uso doméstico de faiança, porcelana e grés fino',
                'Fabricação de artigos de ornamentação de faiança, porcelana e grés fino',
                'Actividades de decoração de artigos cerâmicos de uso doméstico e ornamental',
                'Fabricação de artigos cerâmicos para usos sanitários',
                'Fabricação de isoladores e peças isolantes em cerâmica',
                'Fabricação de outros produtos em cerâmica para usos técnicos',
                'Fabricação de outros produtos cerâmicos não refractários',
                'Fabricação de cimento, cal e gesso',
                'Fabricação de cimento',
                'Fabricação de cal e gesso',
                'Fabricação de cal',
                'Fabricação de gesso',
                'Fabricação de produtos de betão, gesso e cimento',
                'Fabricação de produtos de betão para a construção',
                'Fabricação de produtos de gesso para a construção',
                'Fabricação de betão pronto',
                'Fabricação de argamassas',
                'Fabricação de produtos de fibrocimento',
                'Fabricação de outros produtos de betão, gesso e cimento',
                'Serragem, corte e acabamento de rochas ornamentais e de outras pedras de construção',
                'Fabricação de artigos de mármore e de rochas similares',
                'Fabricação de artigos em ardósia (lousa)',
                'Fabricação de artigos de granito e de rochas, n.e.',
                'Fabricação de produtos abrasivos e de outros produtos minerais não metálicos',
                'Fabricação de produtos abrasivos',
                'Fabricação de outros produtos minerais não metálicos, n.e.',
                'Fabricação de misturas betuminosas',
                'Fabricação de outros produtos minerais não metálicos diversos, n.e.',
                'Indústrias metalúrgicas de base',
                'Siderurgia e fabricação de ferro-ligas',
                'Fabricação de tubos, condutas, perfis ocos e respectivos acessórios, de aço',
                'Outras actividades da primeira transformação do aço',
                'Estiragem a frio',
                'Laminagem a frio de arco ou banda',
                'Perfilagem a frio',
                'Trefilagem a frio',
                'Obtenção e primeira transformação de metais preciosos e de outros metais não ferrosos',
                'Obtenção e primeira transformação de metais preciosos',
                'Obtenção e primeira transformação de alumínio',
                'Obtenção e primeira transformação de chumbo, zinco e estanho',
                'Obtenção e primeira transformação de cobre',
                'Obtenção e primeira transformação de outros metais não ferrosos',
                'Tratamento de combustível nuclear',
                'Fundição de metais ferrosos e não ferrosos',
                'Fundição de ferro fundido',
                'Fundição de aço',
                'Fundição de metais leves',
                'Fundição de outros metais não ferrosos',
                'Fabricação de produtos metálicos, excepto máquinas e equipamentos',
                'Fabricação de elementos de construção em metal',
                'Fabricação de estruturas de construções metálicas',
                'Fabricação de portas, janelas e elementos similares em metal',
                'Fabricação de reservatórios, recipientes, caldeiras e radiadores metálicos para aquecimento central',
                'Fabricação de caldeiras e radiadores para aquecimento central',
                'Fabricação de outros reservatórios e recipientes metálicos',
                'Fabricação de geradores de vapor (excepto caldeiras para aquecimento central)',
                'Fabricação de armas e munições',
                'Fabricação de armas de caça, de desporto e defesa',
                'Fabricação de armamento',
                'Fabricação de produtos forjados, estampados e laminados; metalurgia dos pós',
                'Fabricação de produtos forjados, estampados e laminados',
                'Fabricação de produtos por pulverometalurgia',
                'Tratamento e revestimento de metais; actividades de mecânica geral',
                'Tratamento e revestimento de metais',
                'Actividades de mecânica geral',
                'Fabricação de cutelaria, ferramentas e ferragens',
                'Fabricação de cutelaria',
                'Fabricação de fechaduras, dobradiças e de outras ferragens',
                'Fabricação de ferramentas',
                'Fabricação de ferramentas manuais',
                'Fabricação de ferramentas mecânicas',
                'Fabricação de peças sinterizadas',
                'Fabricação de moldes metálicos',
                'Fabricação de outros produtos metálicos',
                'Fabricação de embalagens metálicas pesadas',
                'Fabricação de embalagens metálicas ligeiras',
                'Fabricação de produtos de arame, correntes e molas metálicas',
                'Fabricação de produtos de arame',
                'Fabricação de molas',
                'Fabricação de correntes metálicas',
                'Fabricação de rebites, parafusos e porcas',
                'Fabricação de outros produtos metálicos, n.e.',
                'Fabricação de louça metálica e artigos de uso doméstico',
                'Fabricação de outros produtos metálicos diversos, n.e.',
                'Fabricação de equipamentos informáticos, equipamento para comunicações e produtos electrónicos e ópticos',
                'Fabricação de componentes e de placas, electrónicos',
                'Fabricação de componentes electrónicos',
                'Fabricação de placas de circuitos electrónicos',
                'Fabricação de computadores e de equipamento periférico',
                'Fabricação de aparelhos e de equipamentos para comunicações',
                'Fabricação de receptores de rádio e de televisão e bens de consumo similares',
                'Fabricação de instrumentos e aparelhos de medida, verificação e navegação; relógios e material de relojoaria',
                'Fabricação de instrumentos e aparelhos de medida, verificação e navegação',
                'Fabricação de contadores de electricidade, gás, água e de outros líquidos',
                'Fabricação de instrumentos e aparelhos de medida, verificação, navegação e outros fins, n.e.',
                'Fabricação de relógios e material de relojoaria',
                'Fabricação de equipamentos de radiação, electromedicina e electroterapêutico',
                'Fabricação de instrumentos e de equipamentos, ópticos e fotográficos',
                'Fabricação de instrumentos e equipamentos ópticos não oftálmicos',
                'Fabricação de material fotográfico e cinematográfico',
                'Fabricação de suportes de informação magnéticos e ópticos',
                'Fabricação de equipamento eléctrico',
                'Fabricação de motores, geradores e transformadores eléctricos e fabricação de material de distribuição e de controlo para instalações eléctricas',
                'Fabricação de motores, geradores e transformadores eléctricos',
                'Fabricação de material de distribuição e de controlo para instalações eléctricas',
                'Fabricação de material de distribuição e de controlo para instalações eléctricas de alta tensão',
                'Fabricação de material de distribuição e de controlo para instalações eléctricas de baixa tensão',
                'Fabricação de acumuladores e pilhas',
                'Fabricação de fios e cabos isolados e seus acessórios',
                'Fabricação de cabos de fibra óptica',
                'Fabricação de outros fios e cabos eléctricos e electrónicos',
                'Fabricação de dispositivos e acessórios para instalações eléctricas, de baixa tensão',
                'Fabricação de lâmpadas eléctricas e de outro equipamento de iluminação',
                'Fabricação de aparelhos para uso doméstico',
                'Fabricação de electrodomésticos',
                'Fabricação de aparelhos não eléctricos para uso doméstico',
                'Fabricação de outro equipamento eléctrico',
                'Fabricação de máquinas e de equipamentos, n.e.',
                'Fabricação de máquinas e de equipamentos para uso geral',
                'Fabricação de motores e turbinas, excepto motores para aeronaves, automóveis e motociclos',
                'Fabricação de equipamento hidráulico e pneumático',
                'Fabricação de outras bombas e compressores',
                'Fabricação de outras torneiras e válvulas',
                'Fabricação de rolamentos, de engrenagens e de outros órgãos de transmissão',
                'Fabricação de outras máquinas para uso geral',
                'Fabricação de fornos e queimadores',
                'Fabricação de equipamento de elevação e de movimentação',
                'Fabricação de ascensores e monta cargas, escadas e passadeiras rolantes',
                'Fabricação de equipamentos de elevação e de movimentação, n.e.',
                'Fabricação de máquinas e equipamento de escritório, excepto computadores e equipamento periférico',
                'Fabricação de máquinas-ferramentas portáteis com motor',
                'Fabricação de equipamento não doméstico para refrigeração e ventilação',
                'Fabricação de outras máquinas para uso geral, n.e.',
                'Fabricação de máquinas de acondicionamento e de embalagem',
                'Fabricação de balanças e de outro equipamento para pesagem',
                'Fabricação de outras máquinas diversas de uso geral, n.e.',
                'Fabricação de máquinas e de tractores para a agricultura, pecuária e silvicultura',
                'Fabricação de máquinas-ferramentas, excepto portáteis',
                'Fabricação de máquinas-ferramentas para metais',
                'Fabricação de outras máquinas-ferramentas',
                'Fabricação de outras máquinas e equipamento para uso específico',
                'Fabricação de máquinas para a metalurgia',
                'Fabricação de máquinas para as indústrias extractivas e para a construção',
                'Fabricação de máquinas para as indústrias alimentares, das bebidas e do tabaco',
                'Fabricação de máquinas para as indústrias têxtil, do vestuário e do couro',
                'Fabricação de máquinas para as indústrias do papel e do cartão',
                'Fabricação de máquinas para as indústrias do plástico e da borracha',
                'Fabricação de outras máquinas e equipamento para uso específico, n.e.',
                'Fabricação de máquinas para as indústrias de materiais de construção, cerâmica e vidro',
                'Fabricação de outras máquinas diversas para uso específico, n.e.',
                'Fabricação de veículos automóveis, reboques, semi-reboques e componentes para veículos automóveis',
                'Fabricação de veículos automóveis',
                'Fabricação de carroçarias, reboques e semi-reboques',
                'Fabricação de componentes e acessórios para veículos automóveis',
                'Fabricação de equipamento eléctrico e electrónico para veículos automóveis',
                'Fabricação de outros componentes e acessórios para veículos automóveis',
                'Fabricação de outro equipamento de transporte',
                'Construção naval',
                'Construção de embarcações e estruturas flutuantes, excepto de recreio e desporto',
                'Construção de embarcações metálicas e estruturas flutuantes, excepto de recreio e desporto',
                'Construção de embarcações não metálicas, excepto de recreio e desporto',
                'Construção de embarcações de recreio e desporto',
                'Fabricação de material circulante para caminhos-de-ferro',
                'Fabricação de aeronaves, de veículos espaciais e equipamento relacionado',
                'Fabricação de veículos militares de combate',
                'Fabricação de equipamento de transporte, n.e.',
                'Fabricação de motociclos',
                'Fabricação de bicicletas e veículos para inválidos',
                'Fabricação de outro equipamento de transporte, n.e.',
                'Fabricação de mobiliário e de colchões',
                'Fabricação de mobiliário para escritório e comércio',
                'Fabricação de mobiliário de cozinha',
                'Fabricação de colchoaria',
                'Fabricação de mobiliário para outros fins',
                'Fabricação de mobiliário de madeira para outros fins',
                'Fabricação de mobiliário metálico para outros fins',
                'Fabricação de mobiliário de outros materiais para outros fins',
                'Actividades de acabamento de mobiliário',
                'Outras indústrias transformadoras',
                'Fabricação de joalharia, ourivesaria, bijutaria e artigos similares; cunhagem de moedas',
                'Cunhagem de moedas',
                'Fabricação de joalharia, ourivesaria e artigos similares',
                'Fabricação de filigranas',
                'Fabricação de artigos de joalharia e de outros artigos de ourivesaria',
                'Trabalho de diamantes e de outras pedras preciosas ou semi-preciosas para joalharia e uso industrial',
                'Fabricação de bijutarias',
                'Fabricação de instrumentos musicais',
                'Fabricação de artigos de desporto',
                'Fabricação de jogos e de brinquedos',
                'Fabricação de instrumentos e material médico-cirúrgico',
                'Fabricação de material óptico oftálmico',
                'Fabricação de material ortopédico e próteses e de instrumentos médico-cirúrgicos',
                'Indústrias transformadoras, n.e.',
                'Fabricação de vassouras, escovas e pincéis',
                'Outras indústrias transformadoras, n.e.',
                'Fabricação de canetas, lápis e similares',
                'Fabricação de fechos de correr, botões e similares',
                'Fabricação de guarda-sóis e chapéus de chuva',
                'Fabricação de equipamento de protecção e segurança',
                'Fabricação de caixões mortuários em madeira',
                'Outras indústrias transformadoras diversas, n.e.',
                'Reparação, manutenção e instalação de máquinas e equipamentos',
                'Reparação e manutenção de produtos metálicos, máquinas e equipamentos',
                'Reparação e manutenção de produtos metálicos (excepto máquinas e equipamentos)',
                'Reparação e manutenção de máquinas e equipamentos',
                'Reparação e manutenção de equipamento electrónico e óptico',
                'Reparação e manutenção de equipamento eléctrico',
                'Reparação e manutenção de embarcações',
                'Reparação e manutenção de aeronaves e de veículos espaciais',
                'Reparação e manutenção de outro equipamento de transporte',
                'Reparação e manutenção de outro equipamento',
                'Instalação de máquinas e de equipamentos industriais',
                'ELECTRICIDADE, GÁS, VAPOR, ÁGUA QUENTE E FRIA E AR FRIO',
                'Electricidade, gás, vapor, água quente e fria e ar frio',
                'Produção, transporte, distribuição e comércio de electricidade',
                'Produção de electricidade',
                'Produção de electricidade de origem hídrica',
                'Produção de electricidade de origem térmica',
                'Produção de electricidade de origem eólica, geotérmica, solar e de origem, n.e.',
                'Transporte de electricidade',
                'Distribuição de electricidade',
                'Comércio de electricidade',
                'Produção de gás; distribuição de combustíveis gasosos por condutas; comércio de gás por condutas',
                'Produção de gás',
                'Distribuição de combustíveis gasosos por condutas',
                'Comércio de gás por condutas',
                'Produção e distribuição de vapor, água quente e fria e ar frio por conduta; produção de gelo',
                'Produção e distribuição de vapor, água quente e fria e ar frio por conduta',
                'Produção de gelo',
                'CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO DE ÁGUA; SANEAMENTO, GESTÃO DE RESÍDUOS E DESPOLUIÇÃO',
                'Captação, tratamento e distribuição de água',
                'Captação e tratamento de água',
                'Distribuição de água',
                'Recolha, drenagem e tratamento de águas residuais',
                'Recolha e drenagem de águas residuais',
                'Tratamento de águas residuais',
                'Recolha, tratamento e eliminação de resíduos; valorização de materiais',
                'Recolha de resíduos',
                'Recolha de resíduos não perigosos',
                'Recolha de resíduos inertes',
                'Recolha de outros resíduos não perigosos',
                'Recolha de resíduos perigosos',
                'Tratamento e eliminação de resíduos',
                'Tratamento e eliminação de resíduos não perigosos',
                'Tratamento e eliminação de resíduos inertes',
                'Tratamento e eliminação de outros resíduos não perigosos',
                'Tratamento e eliminação de resíduos perigosos',
                'Valorização de materiais',
                'Desmantelamento de equipamentos e bens, em fim de vida',
                'Desmantelamento de veículos automóveis, em fim de vida',
                'Desmantelamento de equipamentos eléctricos e electrónicos, em fim de vida',
                'Desmantelamento de outros equipamentos e bens, em fim de vida',
                'Valorização de resíduos seleccionados',
                'Valorização de resíduos metálicos',
                'Valorização de resíduos não metálicos',
                'Descontaminação e actividades similares',
                'CONSTRUÇÃO',
                'Promoção imobiliária (desenvolvimento de projectos de edifícios); construção de edifícios',
                'Promoção imobiliária (desenvolvimento de projectos de edifícios)',
                'Construção de edifícios (residenciais e não residenciais)',
                'Engenharia civil',
                'Construção de estradas, pontes, túneis, pistas de aeroportos e vias férreas',
                'Construção de estradas e pistas de aeroportos',
                'Construção de vias férreas',
                'Construção de pontes e túneis',
                'Construção de redes de transporte de águas, de esgotos, de distribuição de energia, de telecomunicações e de outras redes',
                'Construção de redes de transporte de águas, de esgotos e de outros fluidos',
                'Construção de redes de transporte e distribuição de electricidade e redes de telecomunicações',
                'Construção de outras obras de engenharia civil',
                'Engenharia hidráulica',
                'Construção de outras obras de engenharia civil, n.e.',
                'Actividades especializadas de construção',
                'Demolição e preparação dos locais de construção',
                'Demolição',
                'Preparação dos locais de construção',
                'Perfurações e sondagens',
                'Instalação eléctrica, de canalizações, de climatização e outras instalações',
                'Instalação eléctrica',
                'Instalação de canalizações e de climatização',
                'Instalação de canalizações',
                'Instalação de climatização',
                'Outras instalações em construções',
                'Actividades de acabamento em edifícios',
                'Estucagem',
                'Montagem de trabalhos de carpintaria e de caixilharia',
                'Revestimento de pavimentos e de paredes',
                'Pintura e colocação de vidros',
                'Outras actividades de acabamento em edifícios',
                'Outras actividades especializadas de construção',
                'Actividades de colocação de coberturas',
                'Outras actividades especializadas de construção, n.e.',
                'Aluguer de equipamento de construção e de demolição, com operador',
                'Outras actividades especializadas de construção diversas, n.e.',
                'COMÉRCIO POR GROSSO E A RETALHO; REPARAÇÃO DE VEÍCULOS AUTOMÓVEIS E MOTOCICLOS',
                'Comércio, manutenção e reparação, de veículos automóveis e motociclos',
                'Comércio de veículos automóveis',
                'Comércio de veículos automóveis ligeiros',
                'Comércio de outros veículos automóveis',
                'Manutenção e reparação de veículos automóveis',
                'Comércio de peças e acessórios para veículos automóveis',
                'Comércio por grosso de peças e acessórios para veículos automóveis',
                'Comércio a retalho de peças e acessórios para veículos automóveis',
                'Comércio, manutenção e reparação de motociclos, de suas peças e acessórios',
                'Comércio por grosso e a retalho de motociclos, de suas peças e acessórios',
                'Manutenção e reparação de motociclos, de suas peças e acessórios',
                'Comércio por grosso (inclui agentes), excepto de veículos automóveis e motociclos',
                'Agentes do comércio por grosso',
                'Agentes do comércio por grosso de matérias-primas agrícolas e têxteis, animais vivos e produtos semi-acabados',
                'Agentes do comércio por grosso de combustíveis, minérios, metais e de produtos químicos para a indústria',
                'Agentes do comércio por grosso de madeira e materiais de construção',
                'Agentes do comércio por grosso de máquinas, equipamento industrial, embarcações e aeronaves',
                'Agentes do comércio por grosso de mobiliário, artigos para uso doméstico e ferragens',
                'Agentes do comércio por grosso de têxteis, vestuário, calçado e artigos de couro',
                'Agentes do comércio por grosso de produtos alimentares, bebidas e tabaco',
                'Agentes especializados do comércio por grosso de outros produtos',
                'Agentes do comércio por grosso misto sem predominância',
                'Comércio por grosso de produtos agrícolas brutos e animais vivos',
                'Comércio por grosso de cereais, tabaco e cortiça em bruto, sementes, outras matérias-primas agrícolas e alimentos para animais',
                'Comércio por grosso de alimentos para animais',
                'Comércio por grosso de tabaco em bruto',
                'Comércio por grosso de cortiça em bruto',
                'Comércio por grosso de cereais, sementes, leguminosas, oleaginosas e outras matérias-primas agrícolas',
                'Comércio por grosso de flores e plantas',
                'Comércio por grosso de animais vivos',
                'Comércio por grosso de peles e couro',
                'Comércio por grosso de produtos alimentares, bebidas e tabaco',
                'Comércio por grosso de fruta e de produtos hortícolas',
                'Comércio por grosso de fruta e de produtos hortícolas, excepto batata',
                'Comércio por grosso de batata',
                'Comércio por grosso de carne e produtos à base de carne',
                'Comércio por grosso de leite e derivados, ovos, azeite, óleos e gorduras alimentares',
                'Comércio por grosso de leite, seus derivados e ovos',
                'Comércio por grosso de azeite, óleos e gorduras alimentares',
                'Comércio por grosso de bebidas',
                'Comércio por grosso de bebidas alcoólicas',
                'Comércio por grosso de bebidas não alcoólicas',
                'Comércio por grosso de tabaco',
                'Comércio por grosso de açúcar, chocolate e produtos de confeitaria',
                'Comércio por grosso de açúcar',
                'Comércio por grosso de chocolate e de produtos de confeitaria',
                'Comércio por grosso de café, chá, cacau e especiarias',
                'Comércio por grosso de outros produtos alimentares',
                'Comércio por grosso de peixe, crustáceos e moluscos',
                'Comércio por grosso de outros produtos alimentares, n.e.',
                'Comércio por grosso não especializado de produtos alimentares, bebidas e tabaco',
                'Comércio por grosso de bens de consumo, excepto alimentares, bebidas e tabaco',
                'Comércio por grosso de têxteis',
                'Comércio por grosso de vestuário e calçado',
                'Comércio por grosso de vestuário e de acessórios',
                'Comércio por grosso de calçado',
                'Comércio por grosso de electrodomésticos, aparelhos de rádio e de televisão',
                'Comércio por grosso de louças em cerâmica e em vidro e produtos de limpeza',
                'Comércio por grosso de louças em cerâmica e em vidro',
                'Comércio por grosso de produtos de limpeza',
                'Comércio por grosso de perfumes e de produtos de higiene',
                'Comércio por grosso de produtos farmacêuticos',
                'Comércio por grosso de móveis para uso doméstico, carpetes, tapetes e artigos de iluminação',
                'Comércio por grosso de relógios e de artigos de ourivesaria e joalharia',
                'Outro comércio por grosso de bens de consumo',
                'Comércio por grosso de artigos de papelaria',
                'Comércio por grosso de livros, revistas e jornais',
                'Comércio por grosso de brinquedos, jogos e artigos de desporto',
                'Outro comércio por grosso de bens de consumo, n.e.',
                'Comércio por grosso de equipamento das tecnologias de informação e comunicação ( TIC)',
                'Comércio por grosso de computadores, equipamentos periféricos e programas informáticos',
                'Comércio por grosso de equipamentos electrónicos, de telecomunicações e suas partes',
                'Comércio por grosso de outras máquinas, equipamentos e suas partes',
                'Comércio por grosso de máquinas e equipamentos, agrícolas',
                'Comércio por grosso de máquinas-ferramentas',
                'Comércio por grosso de máquinas para a indústria extractiva, construção e engenharia civil',
                'Comércio por grosso de máquinas para a indústria têxtil, máquinas de costura e de tricotar',
                'Comércio por grosso de mobiliário de escritório',
                'Comércio por grosso de outras máquinas e material de escritório',
                'Comércio por grosso de outras máquinas e equipamentos',
                'Comércio por grosso de combustíveis, metais, materiais de construção, ferragens e outros produtos n.e.',
                'Comércio por grosso de combustíveis sólidos, líquidos, gasosos e produtos derivados',
                'Comércio por grosso de produtos petrolíferos',
                'Comércio por grosso de combustíveis sólidos, líquidos e gasosos, não derivados do petróleo',
                'Comércio por grosso de minérios e de metais',
                'Comércio por grosso de madeira, de materiais de construção e equipamento sanitário',
                'Comércio por grosso de madeira em bruto e de produtos derivados',
                'Comércio por grosso de materiais de construção (excepto madeira) e equipamento sanitário',
                'Comércio por grosso de ferragens, ferramentas manuais e artigos para canalizações e aquecimento',
                'Comércio por grosso de produtos químicos',
                'Comércio por grosso de outros bens intermédios',
                'Comércio por grosso de fibras têxteis naturais, artificiais e sintéticas',
                'Comércio por grosso de outros bens intermédios, n.e.',
                'Comércio por grosso de desperdícios e sucata',
                'Comércio por grosso de sucatas e de desperdícios metálicos',
                'Comércio por grosso de desperdícios têxteis, de cartão e papéis velhos',
                'Comércio por grosso de desperdícios de materiais, n.e.',
                'Comércio por grosso não especializado',
                'Comércio a retalho, excepto de veículos automóveis e motociclos',
                'Comércio a retalho em estabelecimentos não especializados',
                'Comércio a retalho em estabelecimentos não especializados, com predominância de produtos alimentares, bebidas ou tabaco',
                'Comércio a retalho em supermercados e hipermercados',
                'Comércio a retalho em outros estabelecimentos não especializados, com predominância de produtos alimentares, bebidas ou tabaco',
                'Comércio a retalho em estabelecimentos não especializados, sem predominância de produtos alimentares, bebidas ou tabaco',
                'Comércio a retalho não especializado, sem predominância de produtos alimentares, bebidas ou tabaco, em grandes armazéns e similares',
                'Comércio a retalho em outros estabelecimentos não especializados, sem predominância de produtos alimentares, bebidas ou tabaco',
                'Comércio a retalho de produtos alimentares, bebidas e tabaco, em estabelecimentos especializados',
                'Comércio a retalho de frutas e produtos hortícolas, em estabelecimentos especializados',
                'Comércio a retalho de carne e produtos à base de carne, em estabelecimentos especializados',
                'Comércio a retalho de peixe, crustáceos e moluscos, em estabelecimentos especializados',
                'Comércio a retalho de pão, de produtos de pastelaria e de confeitaria, em estabelecimentos especializados',
                'Comércio a retalho de bebidas, em estabelecimentos especializados',
                'Comércio a retalho de tabaco, em estabelecimentos especializados',
                'Comércio a retalho de outros produtos alimentares, em estabelecimentos especializados',
                'Comércio a retalho de leite e de derivados, em estabelecimentos especializados',
                'Comércio a retalho de produtos alimentares, naturais e dietéticos, em estabelecimentos especializados',
                'Outro comércio a retalho de produtos alimentares, em estabelecimentos especializados, n.e.',
                'Comércio a retalho de combustível para veículos a motor, em estabelecimentos especializados',
                'Comércio a retalho de equipamento das tecnologias de informação e comunicação (TIC), em estabelecimentos especializados',
                'Comércio a retalho de computadores, unidades periféricas e programas informáticos, em estabelecimentos especializados',
                'Comércio a retalho de equipamento de telecomunicações, em estabelecimentos especializados',
                'Comércio a retalho de equipamento audiovisual, em estabelecimentos especializados',
                'Comércio a retalho de outro equipamento para uso doméstico, em estabelecimentos especializados',
                'Comércio a retalho de têxteis, em estabelecimentos especializados',
                'Comércio a retalho de ferragens, tintas, vidros, equipamento sanitário, ladrilhos e similares, em estabelecimentos especializados',
                'Comércio a retalho de ferragens e de vidro plano, em estabelecimentos especializados',
                'Comércio a retalho de tintas, vernizes e produtos similares, em estabelecimentos especializados',
                'Comércio a retalho de material de bricolage, equipamento sanitário, ladrilhos e materiais similares, em estabelecimentos especializados',
                'Comércio a retalho de carpetes, tapetes, cortinados e revestimentos para paredes e pavimentos, em estabelecimentos especializados',
                'Comércio a retalho de electrodomésticos, em estabelecimentos especializados',
                'Comércio a retalho de móveis, de artigos de iluminação e de outros artigos para o lar, em estabelecimentos especializados',
                'Comércio a retalho de mobiliário e artigos de iluminação, em estabelecimentos especializados',
                'Comércio a retalho de louças, cutelaria e de outros artigos similares para uso doméstico, em estabelecimentos especializados',
                'Comércio a retalho de outros artigos para o lar, n.e., em estabelecimentos especializados',
                'Comércio a retalho de bens culturais e recreativos, em estabelecimentos especializados',
                'Comércio a retalho de livros, em estabelecimentos especializados',
                'Comércio a retalho de jornais, revistas e artigos de papelaria, em estabelecimentos especializados',
                'Comércio a retalho de discos, CD, DVD, cassetes e similares, em estabelecimentos especializados',
                'Comércio a retalho de artigos de desporto, de campismo e lazer, em estabelecimentos especializados',
                'Comércio a retalho de jogos e brinquedos, em estabelecimentos especializados',
                'Comércio a retalho de outros produtos, em estabelecimentos especializados',
                'Comércio a retalho de vestuário, em estabelecimentos especializados',
                'Comércio a retalho de vestuário para adultos, em estabelecimentos especializados',
                'Comércio a retalho de vestuário para bebés e crianças, em estabelecimentos especializados',
                'Comércio a retalho de calçado e artigos de couro, em estabelecimentos especializados',
                'Comércio a retalho de calçado, em estabelecimentos especializados',
                'Comércio a retalho de marroquinaria e artigos de viagem, em estabelecimentos especializados',
                'Comércio a retalho de produtos farmacêuticos, em estabelecimentos especializados',
                'Comércio a retalho de produtos médicos e ortopédicos, em estabelecimentos especializados',
                'Comércio a retalho de produtos cosméticos e de higiene, em estabelecimentos especializados',
                'Comércio a retalho de flores, plantas, sementes, fertilizantes, animais de companhia e respectivos alimentos, em estabelecimentos especializados',
                'Comércio a retalho de flores, plantas, sementes e fertilizantes, em estabelecimentos especializados',
                'Comércio a retalho de animais de companhia e respectivos alimentos, em estabelecimentos especializados',
                'Comércio a retalho de relógios e de artigos de ourivesaria e joalharia, em estabelecimentos especializados',
                'Comércio a retalho de outros produtos novos, em estabelecimentos especializados',
                'Comércio a retalho de máquinas e de outro material de escritório, em estabelecimentos especializados',
                'Comércio a retalho de material óptico, fotográfico, cinematográfico e de instrumentos de precisão, em estabelecimentos especializados',
                'Comércio a retalho de combustíveis para uso doméstico, em estabelecimentos especializados',
                'Comércio a retalho de outros produtos novos, em estabelecimentos especializados, n.e.',
                'Comércio a retalho de artigos em segunda mão, em estabelecimentos especializados',
                'Comércio a retalho em bancas, feiras e unidades móveis de venda',
                'Comércio a retalho em bancas, feiras e unidades móveis de venda, de produtos alimentares, bebidas e tabaco',
                'Comércio a retalho em bancas, feiras e unidades móveis de venda, de têxteis, vestuário, calçado, malas e similares',
                'Comércio a retalho em bancas, feiras e unidades móveis de venda, de outros produtos',
                'Comércio a retalho não efectuado em estabelecimentos, bancas, feiras ou unidades móveis de venda',
                'Comércio a retalho por correspondência ou via Internet',
                'Comércio a retalho por outros métodos, não efectuado em estabelecimentos, bancas, feiras ou unidades móveis de venda',
                'TRANSPORTES E ARMAZENAGEM',
                'Transportes terrestres e transportes por oleodutos ou gasodutos',
                'Transporte interurbano de passageiros por caminho-de-ferro',
                'Transporte de mercadorias por caminho-de-ferro',
                'Outros transportes terrestres de passageiros',
                'Transportes terrestres, urbanos e suburbanos, de passageiros',
                'Transporte ocasional de passageiros em veículos ligeiros',
                'Outros transportes terrestres de passageiros, n.e.',
                'Transporte interurbano em autocarros',
                'Outros transportes terrestres de passageiros diversos, n.e.',
                'Transportes rodoviários de mercadorias e actividades de mudanças',
                'Transportes rodoviários de mercadorias',
                'Actividades de mudanças, por via rodoviária',
                'Transportes por oleodutos ou gasodutos',
                'Transportes por água',
                'Transportes marítimos de passageiros',
                'Transportes marítimos não costeiros de passageiros',
                'Transportes costeiros e locais de passageiros',
                'Transportes marítimos de mercadorias',
                'Transportes de passageiros por vias navegáveis interiores',
                'Transportes de mercadorias por vias navegáveis interiores',
                'Transportes aéreos',
                'Transportes aéreos de passageiros',
                'Transportes aéreos de mercadorias e transportes espaciais',
                'Transportes aéreos de mercadorias',
                'Transportes espaciais',
                'Armazenagem e actividades auxiliares dos transportes (inclui manuseamento)',
                'Armazenagem',
                'Armazenagem frigorífica',
                'Armazenagem não frigorífica',
                'Actividades auxiliares dos transportes',
                'Actividades auxiliares e de gestão de infra-estruturas dos transportes terrestres',
                'Gestão de infra-estruturas dos transportes terrestres',
                'Assistência a veículos na estrada',
                'Outras actividades auxiliares dos transportes terrestres',
                'Actividades auxiliares dos transportes por água',
                'Actividades auxiliares dos transportes aéreos',
                'Manuseamento de carga',
                'Actividades dos agentes transitários, aduaneiros e de outras actividades de apoio ao transporte',
                'Organização do transporte',
                'Agentes aduaneiros e similares de apoio ao transporte',
                'Actividades postais e de courier',
                'Actividades postais sujeitas a obrigações do serviço universal',
                'Outras actividades postais e de courier',
                'ALOJAMENTO, RESTAURAÇÃO E SIMILARES',
                'Alojamento',
                'Estabelecimentos hoteleiros',
                'Estabelecimentos hoteleiros com restaurante',
                'Hotéis com restaurante',
                'Pensões com restaurante',
                'Estalagens com restaurante',
                'Pousadas com restaurante',
                'Motéis com restaurante',
                'Hotéis-Apartamentos com restaurante',
                'Aldeamentos turísticos com restaurante',
                'Apartamentos turísticos com restaurante',
                'Outros estabelecimentos hoteleiros com restaurante',
                'Estabelecimentos hoteleiros sem restaurante',
                'Hotéis sem restaurante',
                'Pensões sem restaurante',
                'Apartamentos turísticos sem restaurante',
                'Outros estabelecimentos hoteleiros sem restaurante',
                'Residências para férias e outros alojamentos de curta duração',
                'Alojamento mobilado para turistas',
                'Turismo no espaço rural',
                'Colónias e campos de férias',
                'Outros locais de alojamento de curta duração',
                'Parques de campismo e de caravanismo',
                'Outros locais de alojamento',
                'Restauração e similares',
                'Restaurantes (inclui actividades de restauração em meios móveis)',
                'Restaurantes tipo tradicional',
                'Restaurantes com lugares ao balcão',
                'Restaurantes sem serviço de mesa',
                'Restaurantes típicos',
                'Restaurantes com espaço de dança',
                'Confecção de refeições prontas a levar para casa',
                'Restaurantes, n.e. (inclui actividades de restauração em meios móveis)',
                'Fornecimento de refeições para eventos e outras actividades de serviço de r refeições',
                'Fornecimento de refeições para eventos',
                'Outras actividades de serviço de refeições',
                'Estabelecimentos de bebidas',
                'Cafés',
                'Bares',
                'Pastelarias e casas de chá',
                'Outros estabelecimentos de bebidas sem espectáculo',
                'Estabelecimentos de bebidas com espaço de dança',
                'ACTIVIDADES DE INFORMAÇÃO E DE COMUNICAÇÃO',
                'Actividades de edição',
                'Edição de livros, de jornais e de outras publicações',
                'Edição de livros',
                'Edição de listas destinadas a consulta',
                'Edição de jornais',
                'Edição de revistas e de outras publicações periódicas',
                'Outras actividades de edição',
                'Edição de programas informáticos',
                'Edição de jogos de computador',
                'Edição de outros programas informáticos',
                'Actividades cinematográficas, de vídeo, de produção de programas de televisão, de gravação de som e de edição de música',
                'Actividades cinematográficas, de vídeo e de produção de programas de televisão',
                'Produção de filmes, de vídeos e de programas de televisão',
                'Actividades técnicas de pós-produção para filmes, vídeos e programas de televisão',
                'Distribuição de filmes, de vídeos e de programas de televisão',
                'Projecção de filmes e de vídeos',
                'Actividades de gravação de som e edição de música',
                'Actividades de rádio e de televisão',
                'Actividades de rádio',
                'Actividades de televisão',
                'Telecomunicações',
                'Actividades de telecomunicações por fio',
                'Actividades de telecomunicações sem fio',
                'Actividades de telecomunicações por satélite',
                'Outras actividades de telecomunicações',
                'Consultoria e programação informática e actividades relacionadas',
                'Actividades de programação informática',
                'Actividades de consultoria em informática',
                'Gestão e exploração de equipamento informático',
                'Outras actividades relacionadas com as tecnologias da informação e informática',
                'Actividades dos serviços de informação',
                'Actividades de processamento de dados, domiciliação de informação e actividades relacionadas; portais Web',
                'Actividades de processamento de dados, domiciliação de informação e actividades relacionadas',
                'Portais Web',
                'Outras actividades dos serviços de informação',
                'Actividades de agências de notícias',
                'Outras actividades dos serviços de informação, n.e.',
                'ACTIVIDADES FINANCEIRAS E DE SEGUROS',
                'Actividades de serviços financeiros, excepto seguros e fundos de pensões',
                'Intermediação monetária',
                'Banco central',
                'Outra intermediação monetária',
                'Actividades das sociedades gestoras de participações sociais',
                'Actividades das sociedades gestoras de participações sociais financeiras',
                'Actividades das sociedades gestoras de participações sociais não financeiras',
                'Trusts, fundos e entidades financeiras similares',
                'Outras actividades de serviços financeiros, excepto seguros e fundos de pensões',
                'Actividades de locação financeira',
                'Outras actividades de crédito',
                'Actividades das instituições financeiras de crédito',
                'Actividades das sociedades financeiras para aquisições a crédito',
                'Outras actividades de crédito, n.e.',
                'Outras actividades de serviços financeiros n.e., excepto seguros e fundos de pensões',
                'Actividades de factoring',
                'Outras actividades de serviços financeiros diversos , n.e.,excepto seguros e fundos de pensões',
                'Seguros, resseguros e fundos de pensões, excepto segurança social obrigatória',
                'Seguros',
                'Seguros de vida e outras actividades complementares de segurança social',
                'Seguros de vida',
                'Outras actividades complementares de segurança social',
                'Seguros não vida',
                'Resseguros',
                'Fundos de pensões e regimes profissionais complementares',
                'Actividades auxiliares de serviços financeiros e dos seguros',
                'Actividades auxiliares de serviços financeiros, excepto seguros e fundos de pensões',
                'Administração de mercados financeiros',
                'Actividades de negociação por conta de terceiros em valores mobiliários e outros instrumentos financeiros',
                'Outras actividades auxiliares de serviços financeiros, excepto seguros e fundos de pensões',
                'Actividades auxiliares de seguros e de fundos de pensões',
                'Actividades de avaliação de riscos e danos',
                'Actividades de mediadores de seguros',
                'Outras actividades auxiliares de seguros e fundos de pensões',
                'Actividades de gestão de fundos',
                'ACTIVIDADES IMOBILIÁRIAS',
                'Actividades imobiliárias',
                'Compra e venda de bens imobiliários',
                'Arrendamento de bens imobiliários',
                'Actividades imobiliárias por conta de outrem',
                'Mediação e avaliação imobiliária',
                'Actividades de mediação imobiliária',
                'Actividades de angariação imobiliária',
                'Actividades de avaliação imobiliária',
                'Administração de imóveis por conta de outrem; administração de condomínios',
                'Administração de imóveis por conta de outrem',
                'Administração de condomínios',
                'ACTIVIDADES DE CONSULTORIA, CIENTÍFICAS, TÉCNICAS E SIMILARES',
                'Actividades jurídicas e de contabilidade',
                'Actividades jurídicas e dos cartórios notariais',
                'Actividades jurídicas',
                'Actividades dos cartórios notariais',
                'Actividades de contabilidade e auditoria; consultoria fiscal',
                'Actividades das sedes sociais e de consultoria para a gestão',
                'Actividades das sedes sociais',
                'Actividades de consultoria para os negócios e a gestão',
                'Actividades de relações públicas e comunicação',
                'Outras actividades de consultoria para os negócios e a gestão',
                'Actividades de arquitectura, de engenharia e técnicas afins; actividades de ensaios e de análises técnicas',
                'Actividades de arquitectura, de engenharia e técnicas afins',
                'Actividades de arquitectura',
                'Actividades de engenharia e técnicas afins',
                'Actividades de ensaios e análises técnicas',
                'Actividades de investigação científica e de desenvolvimento',
                'Investigação e desenvolvimento das ciências físicas e naturais',
                'Investigação e desenvolvimento em biotecnologia',
                'Outra investigação e desenvolvimento das ciências físicas e naturais',
                'Investigação e desenvolvimento das ciências sociais e humanas',
                'Publicidade, estudos de mercado e sondagens de opinião',
                'Publicidade',
                'Agências de publicidade',
                'Actividades de representação nos meios de comunicação',
                'Estudos de mercado e sondagens de opinião',
                'Outras actividades de consultoria, científicas, técnicas e similares',
                'Actividades de design',
                'Actividades fotográficas',
                'Actividades de tradução e interpretação',
                'Outras actividades de consultoria, científicas, técnicas e similares, n.e.',
                'Actividades veterinárias',
                'ACTIVIDADES ADMINISTRATIVAS E DOS SERVIÇOS DE APOIO',
                'Actividades de aluguer',
                'Aluguer de veículos automóveis',
                'Aluguer de veículos automóveis ligeiros',
                'Aluguer de veículos automóveis pesados',
                'Aluguer de bens de uso pessoal e doméstico',
                'Aluguer de bens recreativos e desportivos',
                'Aluguer de videocassetes e discos',
                'Aluguer de outros bens de uso pessoal e doméstico',
                'Aluguer de outras máquinas e equipamentos',
                'Aluguer de máquinas e equipamentos agrícolas',
                'Aluguer de máquinas e equipamentos para a construção e engenharia civil',
                'Aluguer de máquinas e equipamentos de escritório (inclui computadores)',
                'Aluguer de meios de transporte marítimo e fluvial',
                'Aluguer de meios de transporte aéreo',
                'Aluguer de outras máquinas e equipamentos, n.e.',
                'Locação de propriedade intelectual e produtos similares, excepto direitos de autor',
                'Actividades de emprego',
                'Actividades das empresas de selecção e colocação de pessoal',
                'Actividades das empresas de trabalho temporário',
                'Outro fornecimento de recursos humanos',
                'Agências de viagem, operadores turísticos, outros serviços de reservas e actividades relacionadas',
                'Agências de viagem e operadores turísticos',
                'Actividades das agências de viagem',
                'Actividades dos operadores turísticos',
                'Outros serviços de reservas e actividades relacionadas',
                'Actividades de investigação e segurança',
                'Actividades de segurança privada',
                'Actividades relacionadas com sistemas de segurança',
                'Actividades de investigação',
                'Actividades relacionadas com edifícios, plantação e manutenção de jardins',
                'Actividades combinadas de apoio aos edifícios',
                'Actividades de limpeza',
                'Actividades de limpeza geral em edifícios',
                'Outras actividades de limpeza em edifícios e em equipamentos industriais',
                'Outras actividades de limpeza',
                'Actividades de desinfecção, desratização e similares',
                'Outras actividades de limpeza, n.e.',
                'Actividades de plantação e manutenção de jardins',
                'Actividades de serviços administrativos e de apoio prestados às empresas',
                'Actividades de serviços administrativos e de apoio',
                'Actividades combinadas de serviços administrativos',
                'Execução de fotocópias, preparação de documentos e outras actividades especializadas de apoio administrativo',
                'Actividades dos centros de chamadas',
                'Organização de feiras, congressos e outros eventos similares',
                'Actividades de serviços de apoio prestados às empresas, n.e.',
                'Actividades de cobranças e avaliação de crédito',
                'Actividades de embalagem',
                'Engarrafamento de gases',
                'Outras actividades de embalagem',
                'Outras actividades de serviços de apoio prestados às empresas, n.e.',
                'ADMINISTRAÇÃO PÚBLICA E DEFESA; SEGURANÇA SOCIAL OBRIGATÓRIA',
                'Administração Pública e Defesa; Segurança Social Obrigatória',
                'Administração Pública em geral, económica e social',
                'Administração Pública em geral',
                'Administração Central',
                'Administração Regional Autónoma',
                'Administração Local',
                'Actividades de apoio à administração pública',
                'Administração Pública - actividades de saúde, educação, culturais e sociais, excepto segurança social obrigatória',
                'Administração Pública - actividades de saúde',
                'Administração Pública - actividades de educação',
                'Administração Pública - actividades da cultura, desporto, recreativas, ambiente, habitação e de outras actividades sociais, excepto segurança social obrigatória',
                'Administração Pública - actividades económicas',
                'Negócios Estrangeiros, Defesa, Justiça, Segurança, Ordem Pública e Protecção Civil',
                'Negócios Estrangeiros',
                'Actividades de Defesa',
                'Actividades de Justiça',
                'Actividades de Segurança e Ordem Pública',
                'Actividades de Protecção Civil',
                'Actividades de Segurança Social Obrigatória',
                'EDUCAÇÃO',
                'Educação',
                'Educação pré-escolar',
                'Ensino básico (1º e 2º Ciclos)',
                'Ensino básico (1º Ciclo)',
                'Ensino básico (2º Ciclo)',
                'Ensinos básico (3º Ciclo) e secundário',
                'Ensinos básico (3º Ciclo) e secundário geral',
                'Ensinos secundário tecnológico, artístico e profissional',
                'Ensinos pós-secundário não superior e superior',
                'Ensino pós-secundário não superior',
                'Ensino superior',
                'Outras actividades educativas',
                'Ensinos desportivo e recreativo',
                'Ensino de actividades culturais',
                'Escolas de condução e pilotagem',
                'Formação profissional, escolas de línguas e outras actividades educativas',
                'Formação profissional',
                'Escolas de línguas',
                'Outras actividades educativas, n.e.',
                'Actividades de serviços de apoio à educação',
                'ACTIVIDADES DE SAÚDE HUMANA E APOIO SOCIAL',
                'Actividades de saúde humana',
                'Actividades dos estabelecimentos de saúde com internamento',
                'Actividades de prática clínica em ambulatório, de medicina dentária e de odontologia',
                'Actividades de prática medica de clínica geral, em ambulatório',
                'Actividades de prática medica de clínica especializada, em ambulatório',
                'Actividades de medicina dentária e odontologia',
                'Outras actividades de saúde humana',
                'Laboratórios de análises clínicas',
                'Actividades de ambulâncias',
                'Actividades de enfermagem',
                'Centros de recolha e bancos de órgãos',
                'Actividades termais',
                'Outras actividades de saúde humana, n.e.',
                'Actividades de apoio social com alojamento',
                'Actividades dos estabelecimentos de cuidados continuados integrados, com alojamento',
                'Actividades dos estabelecimentos para pessoas com doença do foro mental e do abuso de drogas, com alojamento',
                'Actividades de apoio social para pessoas idosas e com deficiência, com alojamento',
                'Actividades de apoio social para pessoas idosas, com alojamento',
                'Actividades de apoio social para pessoas com deficiência, com alojamento',
                'Outras actividades de apoio social com alojamento',
                'Actividades de apoio social para crianças e jovens, com alojamento',
                'Actividades de apoio social com alojamento, n.e.',
                'Actividades de apoio social sem alojamento',
                'Actividades de apoio social para pessoas idosas e com deficiência, sem alojamento',
                'Actividades de apoio social para pessoas idosas, sem alojamento',
                'Actividades de apoio social para pessoas com deficiência, sem alojamento',
                'Outras actividades de apoio social sem alojamento',
                'Actividades de cuidados para crianças, sem alojamento',
                'Outras actividades de apoio social sem alojamento, n.e.',
                'ACTIVIDADES ARTÍSTICAS, DE ESPECTÁCULOS, DESPORTIVAS E RECREATIVAS',
                'Actividades de teatro, de música, de dança e outras actividades artísticas e literárias',
                'Actividades das artes do espectáculo',
                'Actividades de apoio às artes do espectáculo',
                'Criação artística e literária',
                'Exploração de salas de espectáculos e actividades conexas',
                'Actividades das bibliotecas, arquivos, museus e outras actividades culturais',
                'Actividades das bibliotecas e arquivos',
                'Actividades das bibliotecas',
                'Actividades dos arquivos',
                'Actividades dos museus',
                'Actividades dos sítios e monumentos históricos',
                'Actividades dos jardins zoológicos, botânicos e aquários e dos parques e reservas naturais',
                'Actividades dos jardins zoológicos, botânicos e aquários',
                'Actividade dos parques e reservas naturais',
                'Lotarias e outros jogos de aposta',
                'Actividades desportivas, de diversão e recreativas',
                'Actividades desportivas',
                'Gestão de instalações desportivas',
                'Actividades dos clubes desportivos',
                'Actividades de ginásio (fitness)',
                'Outras actividades desportivas',
                'Organismos reguladores das actividades desportivas',
                'Outras actividades desportivas, n.e.',
                'Actividades de diversão e recreativas',
                'Actividades dos parques de diversão e temáticos',
                'Outras actividades de diversão e recreativas',
                'Actividades tauromáquicas',
                'Actividades dos portos de recreio (marinas)',
                'Organização de actividades de animação turística',
                'Outras actividades de diversão e recreativas, n.e.',
                'OUTRAS ACTIVIDADES DE SERVIÇOS',
                'Actividades das organizações associativas',
                'Actividades de organizações económicas, patronais e profissionais',
                'Actividades de organizações económicas e patronais',
                'Actividades de organizações profissionais',
                'Actividades de organizações sindicais',
                'Outras actividades de organizações associativas',
                'Actividades de organizações religiosas',
                'Actividades de organizações políticas',
                'Outras actividades de organizações associativas, n.e.',
                'Associações culturais e recreativas',
                'Associações de defesa do ambiente',
                'Associações de juventude e de estudantes',
                'Associações de pais e encarregados de educação',
                'Outras actividades associativas, n.e.',
                'Reparação de computadores e de bens de uso pessoal e doméstico',
                'Reparação de computadores e de equipamento de comunicação',
                'Reparação de computadores e de equipamento periférico',
                'Reparação de equipamento de comunicação',
                'Reparação de bens de uso pessoal e doméstico',
                'Reparação de televisores e de outros bens de consumo similares',
                'Reparação de electrodomésticos e de outros equipamentos de uso doméstico e para jardim',
                'Reparação de calçado e de artigos de couro',
                'Reparação de mobiliário e similares, de uso doméstico',
                'Reparação de relógios e de artigos de joalharia',
                'Reparação de outros bens de uso pessoal e doméstico',
                'Outras actividades de serviços pessoais',
                'Lavagem e limpeza a seco de têxteis e peles',
                'Actividades de salões de cabeleireiro e institutos de beleza',
                'Salões de cabeleireiro',
                'Institutos de beleza',
                'Actividades funerárias e conexas',
                'Actividades de bem-estar físico',
                'Outras actividades de serviços pessoais, n.e.',
                'Actividades de tatuagem e similares',
                'Actividades dos serviços para animais de companhia',
                'Outras actividades de serviços pessoais diversas, n.e.',
                'ACTIVIDADES DAS FAMÍLIAS EMPREGADORAS DE PESSOAL DOMÉSTICO E ACTIVIDADES DE PRODUÇÃO DAS FAMÍLIAS PARA USO PRÓPRIO',
                'Actividades das famílias empregadoras de pessoal doméstico',
                'Actividades de produção de bens e serviços pelas famílias para uso próprio',
                'Actividades de produção de bens pelas famílias para uso próprio',
                'Actividades de produção de serviços pelas famílias para uso próprio',
                'ACTIVIDADES DOS ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUIÇÕES EXTRA-TERRITORIAIS',
                'Actividades dos organismos internacionais e outras instituições extra-territoriais'
            );
            """
        )

    _logger.info("Migration of values done.")

    # Drop the temporary column
    try:
        cr.execute(
            """
            ALTER TABLE l10n_pt_company_eac
            DROP COLUMN code_tmp;
        """
        )
        _logger.info("Temporary column dropped.")
    except Exception as e:
        _logger.warning(
            f"(3) Could not drop 'code_tmp' column. "
            f"It may not exist or another error occurred: {e}"
        )
